/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReconciliationCasesRouteImport } from './routes/reconciliation-cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReconciliationCasesIndexRouteImport } from './routes/reconciliation-cases/index'
import { Route as ReconciliationCasesCaseIdRouteImport } from './routes/reconciliation-cases/$caseId'

const ReconciliationCasesRoute = ReconciliationCasesRouteImport.update({
  id: '/reconciliation-cases',
  path: '/reconciliation-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationCasesIndexRoute =
  ReconciliationCasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ReconciliationCasesRoute,
  } as any)
const ReconciliationCasesCaseIdRoute =
  ReconciliationCasesCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => ReconciliationCasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reconciliation-cases': typeof ReconciliationCasesRouteWithChildren
  '/reconciliation-cases/$caseId': typeof ReconciliationCasesCaseIdRoute
  '/reconciliation-cases/': typeof ReconciliationCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reconciliation-cases/$caseId': typeof ReconciliationCasesCaseIdRoute
  '/reconciliation-cases': typeof ReconciliationCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reconciliation-cases': typeof ReconciliationCasesRouteWithChildren
  '/reconciliation-cases/$caseId': typeof ReconciliationCasesCaseIdRoute
  '/reconciliation-cases/': typeof ReconciliationCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reconciliation-cases'
    | '/reconciliation-cases/$caseId'
    | '/reconciliation-cases/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reconciliation-cases/$caseId' | '/reconciliation-cases'
  id:
    | '__root__'
    | '/'
    | '/reconciliation-cases'
    | '/reconciliation-cases/$caseId'
    | '/reconciliation-cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReconciliationCasesRoute: typeof ReconciliationCasesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reconciliation-cases': {
      id: '/reconciliation-cases'
      path: '/reconciliation-cases'
      fullPath: '/reconciliation-cases'
      preLoaderRoute: typeof ReconciliationCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation-cases/': {
      id: '/reconciliation-cases/'
      path: '/'
      fullPath: '/reconciliation-cases/'
      preLoaderRoute: typeof ReconciliationCasesIndexRouteImport
      parentRoute: typeof ReconciliationCasesRoute
    }
    '/reconciliation-cases/$caseId': {
      id: '/reconciliation-cases/$caseId'
      path: '/$caseId'
      fullPath: '/reconciliation-cases/$caseId'
      preLoaderRoute: typeof ReconciliationCasesCaseIdRouteImport
      parentRoute: typeof ReconciliationCasesRoute
    }
  }
}

interface ReconciliationCasesRouteChildren {
  ReconciliationCasesCaseIdRoute: typeof ReconciliationCasesCaseIdRoute
  ReconciliationCasesIndexRoute: typeof ReconciliationCasesIndexRoute
}

const ReconciliationCasesRouteChildren: ReconciliationCasesRouteChildren = {
  ReconciliationCasesCaseIdRoute: ReconciliationCasesCaseIdRoute,
  ReconciliationCasesIndexRoute: ReconciliationCasesIndexRoute,
}

const ReconciliationCasesRouteWithChildren =
  ReconciliationCasesRoute._addFileChildren(ReconciliationCasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReconciliationCasesRoute: ReconciliationCasesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
